# Generated by Django 4.2.4 on 2024-09-16 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_number', models.CharField(default='', max_length=255)),
                ('case_date', models.DateField(default=None)),
                ('case_type', models.CharField(choices=[('مخالفات', 'مخالفات'), ('جنح', 'جنح'), ('جنايات', 'جنايات'), ('أحوال شخصية', 'أحوال شخصية'), ('إداري', 'إداري'), ('مجلس دولة', 'مجلس دولة'), ('مدني', 'مدني'), ('تجاري', 'تجاري'), ('عمال', 'عمال')], default='', max_length=255)),
                ('court', models.CharField(default='', max_length=255)),
                ('status', models.CharField(choices=[('جارية', 'جارية'), ('مؤجلة', 'مؤجلة'), ('مؤرشفة', 'مؤرشفة')], default='', max_length=255)),
                ('results', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(default='', max_length=255)),
                ('client_name', models.CharField(default='', max_length=255)),
                ('gender', models.CharField(choices=[('ذكر', 'ذكر'), ('أنثى', 'أنثى')], default='', max_length=255)),
                ('Date_Of_Birth', models.DateField(default=None)),
                ('email', models.EmailField(default='', max_length=255)),
                ('mobile', models.CharField(default='', max_length=255)),
                ('address', models.CharField(default='', max_length=255)),
                ('state', models.CharField(default='', max_length=255)),
                ('city', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Sitting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sitting_number', models.CharField(default='', max_length=255)),
                ('sitting_date', models.DateField(default=None)),
                ('attachments', models.FileField(blank=True, null=True, upload_to='media/')),
                ('notes', models.TextField(blank=True, max_length=255, null=True)),
                ('case_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Myapp.case')),
            ],
        ),
        migrations.AddField(
            model_name='case',
            name='client_FK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Myapp.client'),
        ),
        migrations.CreateModel(
            name='Appointments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateField(default=None)),
                ('notes', models.TextField(blank=True, max_length=255, null=True)),
                ('client_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Myapp.client')),
            ],
        ),
    ]
